name: Feature request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make this project better! Please fill out the details below.

  - type: input
    id: title
    attributes:
      label: Title
      description: A brief title for your feature request
      placeholder: 'Enter feature request title'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the feature request
      placeholder: 'Enter feature request description'
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should this feature be added? What problem does it solve?
      placeholder: 'Enter motivation for the feature'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered
      placeholder: 'Enter alternative solutions'

  - type: input
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: 'Enter additional context'
